// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Week04/api/students/v1"
	"Week04/internal/biz"
	"Week04/internal/data"
	"Week04/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initServer() student.StudentServer {
	studentRepo := data.NewStudentRepo()
	studentUsecase := biz.NewStudentUsecase(studentRepo)
	studentServer := service.NewStudentService(studentUsecase)
	return studentServer
}

// wire.go:

var SuperSet = wire.NewSet(data.NewStudentRepo, biz.NewStudentUsecase, service.NewStudentService)
